# Generated by Django 3.2.18 on 2023-04-21 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назначение')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('hex_value', models.CharField(max_length=7, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('image', models.ImageField(upload_to='films', verbose_name='Пленка')),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(upload_to='panels', verbose_name='Фото панели')),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('tech_info', models.CharField(max_length=5000, verbose_name='Техническое описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('popular', models.IntegerField(default=0, editable=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doors.branch', verbose_name='Назначение')),
                ('colors', models.ManyToManyField(to='doors.Color', verbose_name='Цвета')),
                ('films', models.ManyToManyField(to='doors.Film', verbose_name='Пленки')),
                ('inside_img', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inside_panel', to='doors.panel', verbose_name='Внутреняя панель')),
                ('outside_img', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outside_panel', to='doors.panel', verbose_name='Внешняя панель')),
            ],
        ),
        migrations.CreateModel(
            name='CTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Описание')),
                ('show', models.BooleanField(default=False, verbose_name='Показывать')),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doors.door', verbose_name='Дверь')),
            ],
        ),
    ]
