# Generated by Django 3.2.18 on 2023-04-27 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0002_auto_20230427_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='id',
        ),
        migrations.AddField(
            model_name='door',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, serialize=False),
        ),
    ]
